#!/usr/bin/env bash
# Cryptarch dev runner v2 (CRYPTARCH-9): throwaway Postgres + PgBouncer edge
# + the app, one command. Mirrors the v0.2 topology from doc-cryptarch-edge-spec:
#
#   consumers -> bouncer (published) -> postgres (docker network only)
#
# The app's admin DSN goes direct to Postgres; the ADVERTISED address (what
# users get in connection strings) is the bouncer. NOTE: until CRYPTARCH-11
# ships auth_query + the hba renderer, provisioned users cannot yet auth
# through the bouncer — their connection strings are correct but dead. Not a
# bug; the shim task lights them up.
#
# For a real deployment use docker-compose.yml / a Komodo stack instead.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

PG_NAME=cryptarch-dev-pg
BOUNCER_NAME=cryptarch-dev-bouncer
NET=cryptarch-dev
PG_PORT=${PG_PORT:-55432}
BOUNCER_PORT=${BOUNCER_PORT:-56432}
APP_PORT=${APP_PORT:-8080}
ADMIN_PW=${CRYPTARCH_ADMIN_PASSWORD:-changeme}
BOUNCER_IMAGE=edoburu/pgbouncer:v1.24.1-p1
CONF_DIR="$SCRIPT_DIR/dev-bouncer"

trap 'echo "!! failed — stack may be partially up; teardown: docker rm -f $PG_NAME $BOUNCER_NAME; docker network rm $NET"' ERR

echo ">> docker network $NET"
docker network inspect "$NET" >/dev/null 2>&1 || docker network create "$NET" >/dev/null

# No --rm anywhere: teardown is explicit docker rm -f, and keeping crashed
# containers around preserves their logs (and avoids the rm/run name race).
echo ">> starting Postgres ($PG_NAME) on 127.0.0.1:$PG_PORT (network-internal: $PG_NAME:5432)"
docker rm -f "$PG_NAME" >/dev/null 2>&1 || true
docker run -d --name "$PG_NAME" --network "$NET" \
  -e POSTGRES_PASSWORD=devpass -e POSTGRES_DB=cryptarch \
  -p "127.0.0.1:$PG_PORT:5432" postgres:18 >/dev/null

echo -n ">> waiting for Postgres"
ready=false
for _ in $(seq 1 30); do
  if docker exec "$PG_NAME" pg_isready -U postgres >/dev/null 2>&1; then ready=true; echo " ready"; break; fi
  echo -n "."; sleep 1
done
if ! $ready; then
  echo " timeout — postgres never became ready; last logs:"
  docker logs "$PG_NAME" 2>&1 | tail -20 || true
  exit 1
fi

# ---- bouncer config (dev-initial; Cryptarch renders the hba in v0.2) --------
mkdir -p "$CONF_DIR"

cat > "$CONF_DIR/pgbouncer.ini" <<EOF
; dev harness config — regenerated by run-dev.sh, do not hand-edit
[databases]
; wildcard: any db name routes to the backend. Cross-tenant access through
; the edge is gated by per-database GRANTs on the Postgres side.
* = host=$PG_NAME port=5432

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = hba
auth_hba_file = /etc/pgbouncer/pgbouncer_hba.conf
auth_file = /etc/pgbouncer/userlist.txt
admin_users = pgbadmin
# Mirrors the compose stack: the renderer emits a console hba line per console
# user, so pgbstats has to exist here too or the rendered rule names nobody.
stats_users = pgbstats
; dynamic consumer auth: bouncer resolves provisioned users from Postgres
; itself via the cryptarch.get_auth shim (installed by server-init).
auth_user = cryptarch_auth
auth_dbname = postgres
auth_query = SELECT usename, passwd FROM cryptarch.get_auth(\$1)
; session mode is the v0.2 default: fully transparent to consumers
; (LISTEN/NOTIFY, advisory locks, session state all work). Transaction
; pooling is a deliberate per-server opt-in later.
pool_mode = session
max_client_conn = 100
default_pool_size = 10
; arbitrary consumer drivers (JDBC, npgsql, ORMs) send these at startup;
; without this the edge rejects them.
ignore_startup_parameters = extra_float_digits,options

; pool knobs rendered by Cryptarch (CRYPTARCH-32). MUST stay the last line of
; the [pgbouncer] section: the fragment is headerless (a re-opened section
; header would reset every key above to its default), and last-wins is what
; lets portal values override the baseline above.
%include /etc/pgbouncer/cryptarch_bouncer.ini
EOF

# Stub so the bouncer boots before Cryptarch's first render replaces it
# (pgbouncer errors out on a missing %include target).
cat > "$CONF_DIR/cryptarch_bouncer.ini" <<EOF
; managed by cryptarch — stub until the portal's first edge sync
EOF

# Plaintext secrets are dev-only; the real deployment uses auth_query (v0.2)
# so consumer passwords never live in this file at all.
cat > "$CONF_DIR/userlist.txt" <<EOF
"pgbadmin" "devconsole"
"pgbstats" "devstats"
"postgres" "devpass"
EOF

cat > "$CONF_DIR/pgbouncer_hba.conf" <<EOF
# dev harness initial hba — Cryptarch's renderer replaces this in v0.2
host pgbouncer pgbadmin 0.0.0.0/0 scram-sha-256
host all postgres 0.0.0.0/0 scram-sha-256
EOF

# The bouncer reads these as uid 70 in-container; without chown, world-read
# is the only way (640 would need group 70). Dev-only creds, accepted.
chmod 755 "$CONF_DIR"; chmod 644 "$CONF_DIR"/*

echo ">> starting PgBouncer ($BOUNCER_NAME) on 127.0.0.1:$BOUNCER_PORT"
docker rm -f "$BOUNCER_NAME" >/dev/null 2>&1 || true
docker run -d --name "$BOUNCER_NAME" --network "$NET" \
  -v "$CONF_DIR:/etc/pgbouncer:ro" \
  -p "127.0.0.1:$BOUNCER_PORT:6432" \
  --entrypoint pgbouncer "$BOUNCER_IMAGE" /etc/pgbouncer/pgbouncer.ini >/dev/null

sleep 1
if [ "$(docker inspect -f '{{.State.Running}}' "$BOUNCER_NAME" 2>/dev/null)" != "true" ]; then
  echo "!! bouncer failed to start; logs:"
  docker logs "$BOUNCER_NAME" 2>&1 | tail -10 || true
  exit 1
fi

# At-rest encryption key for stored admin DSNs — generated once, reused.
# -s (not -f): a half-written empty file from an interrupted run regenerates.
KEY_FILE="${CRYPTARCH_KEY_FILE:-.dev-key}"
if [ ! -s "$KEY_FILE" ]; then
  echo ">> generating dev key file $KEY_FILE"
  (umask 077; openssl rand -hex 32 > "$KEY_FILE")
fi
export CRYPTARCH_KEY_FILE="$KEY_FILE"

# Dev convenience: a proper non-superuser panel role + the DBA bootstrap
# (pg_shadow grant + cryptarch schema), so server-init and the CRUD add-flow
# can be exercised exactly as they run in production.
docker exec "$PG_NAME" psql -U postgres -c \
  "CREATE ROLE cryptarch_admin LOGIN CREATEDB CREATEROLE PASSWORD 'testadmin'" >/dev/null 2>&1 || true
docker exec "$PG_NAME" psql -U postgres -c \
  "GRANT SELECT ON pg_shadow TO cryptarch_admin" >/dev/null
docker exec "$PG_NAME" psql -U postgres -c \
  "CREATE SCHEMA IF NOT EXISTS cryptarch AUTHORIZATION cryptarch_admin" >/dev/null

# Dev seed uses the container superuser; the role gate refuses that in
# production. Never set this outside the dev harness.
export CRYPTARCH_ALLOW_SUPERUSER_ADMIN=1
# Dev runs over plain HTTP — Secure cookies would never be sent.
export CRYPTARCH_INSECURE_COOKIES=1

export CRYPTARCH_METADATA_DSN="postgres://postgres:devpass@localhost:$PG_PORT/cryptarch"
export CRYPTARCH_BIND="0.0.0.0:$APP_PORT"
export CRYPTARCH_ADMIN=admin
export CRYPTARCH_ADMIN_PASSWORD="$ADMIN_PW"
export CRYPTARCH_DEFAULT_QUOTA=3
# Admin DSN: direct to Postgres (the private hop). Advertised host/port: the
# BOUNCER — that's what lands in user connection strings, per the topology.
export CRYPTARCH_SEED_SERVER_DSN="postgres://postgres:devpass@localhost:$PG_PORT/postgres"
export CRYPTARCH_SEED_SERVER_NAME=local
export CRYPTARCH_SEED_SERVER_HOST=localhost
export CRYPTARCH_SEED_SERVER_PORT="$BOUNCER_PORT"
# Default "Allowed from" = the dev network's real subnet (docker picks it),
# mirroring the compose stack's out-of-box behavior.
DEV_SUBNET=$(docker network inspect "$NET" -f '{{(index .IPAM.Config 0).Subnet}}' 2>/dev/null || true)
export CRYPTARCH_SEED_SERVER_DEFAULT_CIDR="${DEV_SUBNET}"
# Who may reach the bouncer console (CRYPTARCH-104). REQUIRED here, not
# optional: the dev app runs on the HOST and reaches the bouncer through a
# published port, so the bouncer sees the bridge GATEWAY address (172.x.0.1),
# not 127.0.0.1. Leaving the default would let the first edge sync write an hba
# that locks Cryptarch out of its own console — the sync itself succeeds (the
# old hba is still live when it RELOADs) and every console operation after it
# fails, leaving the server permanently edge_dirty.
export CRYPTARCH_CONSOLE_CIDR="${DEV_SUBNET}"
# In-stack dial path: the bouncer's container name on the dev network.
export CRYPTARCH_SEED_SERVER_STACK_LISTENER="$BOUNCER_NAME:6432"

echo ">> admin login:   admin / $ADMIN_PW"
echo ">> app:           http://<this-host>:$APP_PORT/"
echo ">> bouncer:       127.0.0.1:$BOUNCER_PORT (console: pgbadmin/devconsole db=pgbouncer)"
echo ">> teardown:      docker rm -f $PG_NAME $BOUNCER_NAME && docker network rm $NET"
# The UI is compiled into the binary, so build it first; SKIP_FRONTEND=1 keeps
# whatever frontend/build already holds (or build.rs's placeholder).
if [ -z "${SKIP_FRONTEND:-}" ]; then
  (cd frontend && { [ -d node_modules ] || npm ci; } && npm run build)
fi
exec cargo run --release
